server:
  port: 8083
spring:
  datasource:
    url: ${JDBC-URL:jdbc:postgresql://localhost:5432/dpp?user=postgres&password=123456&useUnicode=true&characterEncoding=utf-8&useSSL=true}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: dzt.studio.dppservice.domain
  mapper-locations: classpath:/mapper/*.xml
jwt:
  expiration: 18000000
  secret: P@ssw02dC1C
  header: X-Token
  prefix:
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
daphost:
  host: ${DAPHOST-HOST:192.168.103.120}
  port: ${DAPHOST-PORT:22}
  user: ${DAPHOST-USER:root}
  password: ${DAPHOST-PASSWORD:Qbkj@2020}
