server:
  port: 8083
spring:
  datasource:
    url: ${JDBC_URL}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: dzt.studio.dppservice.domain
  mapper-locations: classpath:/mapper/*.xml
jwt:
  expiration: 18000000
  secret: P@ssw02dC1C
  header: X-Token
  prefix:
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

daphost:
  host: ${DAPHOST_HOST}
  port: ${DAPHOST_PORT}
  user: ${DAPHOST_USER}
  password: ${DAPHOST_PASSWORD}
