server:
  port: 8083
spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://192.168.103.113:5432/dpp?user=postgres&password=Qbkj@2020&useUnicode=true&characterEncoding=utf-8&useSSL=true}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: dzt.studio.dppservice.domain
  mapper-locations: classpath:/mapper/*.xml
jwt:
  expiration: 18000000
  secret: P@ssw02dC1C
  header: X-Token
  prefix:
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

daphost:
  host: ${DAPHOST_HOST:}
  port: ${DAPHOST_PORT:0}
  user: ${DAPHOST_USER:}
  password: ${DAPHOST_PASSWORD:}

# ~/.kube/config 文件内容
kube:
  config: ${KUBE_CONFIG:}
# 项目环境名
env:
  name: ${ENV_NAME:TEST}
# 发送邮件的邮箱
mail:
  host: ${MAIL_HOST}
  password: ${MAIL_PASSWORD}
  from: ${MAIL_FROM}
